CREATE TABLE ENDERECOS (
  id            BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
  cidade        VARCHAR(64) NOT NULL,
  estado        VARCHAR(2)  NOT NULL,
  logradouro    VARCHAR(64) NOT NULL,
  tipo          VARCHAR(32) NOT NULL,
  created_by    VARCHAR(32),
  created_date  DATETIME,
  modified_by   VARCHAR(32),
  modified_date DATETIME,
  PRIMARY KEY (id)
);

CREATE TABLE CONTATOS (
  id            BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
  data_cadastro DATE,
  idade         INTEGER,
  nome          VARCHAR(64) NOT NULL,
  endereco_id   BIGINT      NOT NULL,
  created_by    VARCHAR(32),
  created_date  DATETIME,
  modified_by   VARCHAR(32),
  modified_date DATETIME,
  PRIMARY KEY (id)
);
ALTER TABLE CONTATOS
  ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (endereco_id) REFERENCES ENDERECOS
  ON DELETE CASCADE;